[2024-01-12T18:45:23.404+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-01-12T18:45:23.410+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-01-12T18:45:23.412+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-12T18:45:23.420+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2024-01-09 00:00:00+00:00
[2024-01-12T18:45:23.425+0000] {standard_task_runner.py:60} INFO - Started process 436 to run task
[2024-01-12T18:45:23.428+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'format_to_parquet_task', 'scheduled__2024-01-09T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpk4w47bka']
[2024-01-12T18:45:23.431+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask format_to_parquet_task
[2024-01-12T18:45:23.447+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-01-12T18:45:23.483+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task scheduled__2024-01-09T00:00:00+00:00 [running]> on host b70544739fe4
[2024-01-12T18:45:23.556+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='format_to_parquet_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-09T00:00:00+00:00'
[2024-01-12T18:45:23.560+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 37, in format_to_parquet
    table = pd.read_csv(src_file)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 753, in get_handle
    handle = gzip.GzipFile(  # type: ignore[assignment]
  File "/usr/local/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/yellow_tripdata_2021-01.csv.gz'
[2024-01-12T18:45:23.570+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=format_to_parquet_task, execution_date=20240109T000000, start_date=20240112T184523, end_date=20240112T184523
[2024-01-12T18:45:23.578+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task format_to_parquet_task ([Errno 2] No such file or directory: '/opt/airflow/yellow_tripdata_2021-01.csv.gz'; 436)
[2024-01-12T18:45:23.603+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-12T18:45:23.621+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
